/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 merch.glb --transform 
Files: merch.glb [5.38MB] > merch-transformed.glb [518.02KB] (90%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/merch-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body_Back_Node.geometry} material={materials.Body_FRONT_2664} />
    </group>
  )
}

useGLTF.preload('/merch-transformed.glb')
