/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 mindchatterBust.gltf --transform 
Files: mindchatterBust.gltf [2.82MB] > mindchatterBust-transformed.glb [269.23KB] (90%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mindchatterBust-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Default.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/mindchatterBust-transformed.glb')
