/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 vinyl.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/vinyl2.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials["Material.001"]}
        position={[0, -0.002, 0]}
        scale={0.89}
      />
      <mesh
        geometry={nodes.Circle002.geometry}
        material={materials["Material.002"]}
        position={[0, 0.006, 0]}
        scale={0.879}
      />
      <mesh
        geometry={nodes.Circle003.geometry}
        material={materials["Material.002"]}
        position={[0, 0.006, 0]}
        scale={0.777}
      />
      <mesh
        geometry={nodes.Circle004.geometry}
        material={materials["Material.002"]}
        position={[0, 0.006, 0]}
        scale={0.699}
      />
      <mesh
        geometry={nodes.Circle005.geometry}
        material={materials["Material.002"]}
        position={[0, 0.006, 0]}
        scale={0.645}
      />
      <mesh
        geometry={nodes.Circle006.geometry}
        material={materials["Material.003"]}
        position={[0, 0, 0.001]}
        scale={0.991}
      />
      <mesh
        geometry={nodes.Circle007.geometry}
        material={materials["Material.004"]}
        position={[0, -0.005, 0.001]}
        scale={1.069}
      />
      <mesh
        geometry={nodes.Circle008.geometry}
        material={materials["Material.004"]}
        position={[0, -0.012, 0.001]}
        scale={2.117}
      />
      <mesh
        geometry={nodes.Text.geometry}
        material={materials["Material.004"]}
        position={[0, 0.015, 0.024]}
        scale={0.096}
      />
      <mesh
        geometry={nodes.z.geometry}
        material={materials["Material.004"]}
        position={[0.218, 0.015, 0.685]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.096}
      />
      <mesh
        geometry={nodes.Circle001.geometry}
        material={materials["Material.002"]}
        position={[0, -0.004, 0]}
        scale={0.879}
      />
      <mesh
        geometry={nodes.Circle009.geometry}
        material={materials["Material.002"]}
        position={[0, -0.011, 0]}
        scale={0.777}
      />
      <mesh
        geometry={nodes.Circle010.geometry}
        material={materials["Material.002"]}
        position={[0, -0.011, 0]}
        scale={0.699}
      />
      <mesh
        geometry={nodes.Circle011.geometry}
        material={materials["Material.002"]}
        position={[0, -0.011, 0]}
        scale={0.645}
      />
      <mesh
        geometry={nodes.Circle012.geometry}
        material={materials["Material.002"]}
        position={[0, -0.012, 0]}
        scale={0.879}
      />
      <mesh
        geometry={nodes.z001.geometry}
        material={materials["Material.004"]}
        position={[-0.327, 0.015, 0.694]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.102}
      />
      <mesh
        geometry={nodes.z002.geometry}
        material={materials["Material.004"]}
        position={[0.613, 0.015, 0.704]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.112}
      />
      <mesh
        geometry={nodes.z003.geometry}
        material={materials["Material.004"]}
        position={[-0.327, 0.007, 0.623]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.059}
      />
      <mesh
        geometry={nodes.Circle013.geometry}
        material={materials["Material.003"]}
        position={[0, -0.005, 0.005]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.991}
      />
      <mesh
        geometry={nodes.Circle014.geometry}
        material={materials["Material.004"]}
        position={[0, 0, 0.005]}
        rotation={[-Math.PI, 0, 0]}
        scale={1.069}
      />
      <mesh
        geometry={nodes.Circle015.geometry}
        material={materials["Material.004"]}
        position={[0, 0.007, 0.005]}
        rotation={[-Math.PI, 0, 0]}
        scale={2.117}
      />
      <mesh
        geometry={nodes.Text001.geometry}
        material={materials["Material.004"]}
        position={[0, -0.02, -0.017]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.096}
      />
      <mesh
        geometry={nodes.z004.geometry}
        material={materials["Material.004"]}
        position={[0.218, -0.036, -0.678]}
        scale={0.096}
      />
      <mesh
        geometry={nodes.z005.geometry}
        material={materials["Material.004"]}
        position={[-0.327, -0.036, -0.687]}
        scale={0.102}
      />
      <mesh
        geometry={nodes.z006.geometry}
        material={materials["Material.004"]}
        position={[0.613, -0.02, -0.697]}
        scale={0.112}
      />
      <mesh
        geometry={nodes.z007.geometry}
        material={materials["Material.004"]}
        position={[-0.327, -0.012, -0.616]}
        scale={0.059}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.003"]}
        position={[0, -0.032, 0.95]}
      />
      <mesh
        geometry={nodes.Text002.geometry}
        material={materials["Material.004"]}
        position={[0.585, -0.022, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.47, 0.494, 0.494]}
      />
      <mesh
        geometry={nodes.Text003.geometry}
        material={materials["Material.004"]}
        position={[0.241, -0.022, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.47, 0.494, 0.494]}
      />
      <mesh
        geometry={nodes.Text004.geometry}
        material={materials["Material.004"]}
        position={[-0.061, -0.022, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.47, 0.494, 0.494]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Material.004"]}
        position={[-1.128, -0.026, 0.95]}
      />
      <mesh
        geometry={nodes.Text005.geometry}
        material={materials["Material.004"]}
        position={[-0.909, -0.022, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.494}
      />
    </group>
  );
}
